-- schema.sql  (PostgreSQL 12+)

-- ========== 브랜드 / 지점 ==========
CREATE TABLE IF NOT EXISTS brand (
  brand_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_name VARCHAR(100) NOT NULL,
  brand_owner VARCHAR(100) -- 브랜드 소유 기업명(SPC, CJ 등)
);

CREATE TABLE IF NOT EXISTS brand_branch (
  branch_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id  BIGINT NOT NULL REFERENCES brand(brand_id) ON DELETE CASCADE,
  branch_name VARCHAR(150) NOT NULL,
  latitude    NUMERIC(10,7) NOT NULL,
  longitude   NUMERIC(10,7) NOT NULL,
  is_active   BOOLEAN DEFAULT TRUE
);

-- ========== 프로바이더(카드/통신/브랜드/단체/멤버십) ==========
CREATE TABLE IF NOT EXISTS discount_provider (
  provider_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_name VARCHAR(100) NOT NULL,
  provider_type VARCHAR(20)  NOT NULL CHECK (provider_type IN ('PAYMENT','TELCO','BRAND','AFFILIATION','MEMBERSHIP')),
  app_coupon    BOOLEAN DEFAULT FALSE,   -- 앱 쿠폰 존재 여부
  website_url   VARCHAR(255),
  is_active     BOOLEAN DEFAULT TRUE
);
CREATE TABLE payment_provider_detail (
  provider_id    BIGINT PRIMARY KEY REFERENCES discount_provider(provider_id),
  card_company_code VARCHAR(20)     -- 'KB', 'SHINHAN', ...
);
CREATE TABLE telco_provider_detail (
  provider_id    BIGINT PRIMARY KEY REFERENCES discount_provider(provider_id),
  membership_level_required VARCHAR(50),  -- 기본등급 정보 템플릿
  telco_name       VARCHAR(20) NOT NULL CHECK (telco_name IN ('SKT','KT','LG U+')),
  telco_app_name   VARCHAR(50) NOT NULL CHECK (telco_app_name IN ('T 멤버십', 'KT 멤버십', 'U+ 멤버스'))
);
CREATE TABLE affiliation_provider_detail (
  provider_id     BIGINT PRIMARY KEY REFERENCES discount_provider(provider_id),
  organization_name VARCHAR(150),  -- 'OO회사', 'OO대학교', '교직원 복지몰'
  eligibility_rule TEXT            -- 재직자만, 학생만 등
);
CREATE TABLE membership_provider_detail (
  provider_id     BIGINT PRIMARY KEY REFERENCES discount_provider(provider_id),
  membership_name VARCHAR(50) NOT NULL, -- CJ ONE, L.POINT, 신세계포인트, 해피포인트
  membership_level_required VARCHAR(50)  -- 기본등급 정보 템플릿
);
-- 결제수단 메타(개인화 X, 안내용)
CREATE TABLE IF NOT EXISTS payment_product (
  payment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id   BIGINT NOT NULL REFERENCES discount_provider(provider_id),
  payment_name  VARCHAR(150) NOT NULL,  --카드의정석 NEW우리V카드, 신한카드 YOLO Tasty, 씨티 클리어카드, BLISS.7 카드
  payment_company VARCHAR(50)
);
-- ========== 할인 프로그램 ==========
CREATE TABLE IF NOT EXISTS discount_program (
  discount_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id        BIGINT NOT NULL REFERENCES discount_provider(provider_id) ON DELETE CASCADE,
  discount_name      VARCHAR(150) NOT NULL,
  discount_type      VARCHAR(20)  NOT NULL CHECK (discount_type IN ('PERCENT','AMOUNT','PER_UNIT')),
  discount_amount    NUMERIC(10,2) NOT NULL,    -- 할인율 or 금액
  max_amount         NUMERIC(10,2),         -- 1회 최대 적용 가능한 금액
  max_usage_cnt      INT,                  -- 월 최대 사용 횟수 
  required_level     VARCHAR(50),           -- 요구되는 멤버십 or 카드 등급
  valid_from         DATE,
  valid_to           DATE,
  dow_mask           SMALLINT,               -- day of week mask, 월=0 … 일=6
  time_from          TIME,
  time_to            TIME,
  channel_limit      VARCHAR(20),            -- 'OFFLINE','APP','DELIVERY' 등
  qualification      TEXT,                  -- 적용 조건(전월 실적, 멤버 등급 등)
  application_menu   TEXT,                  -- 적용 가능한 메뉴 목록
  is_active          BOOLEAN DEFAULT TRUE,
  is_discount        BOOLEAN DEFAULT TRUE   -- 중복 적용 가능 여부 결정할 때 사용(False는 적립)
);

ALTER TABLE discount_program
  ADD CONSTRAINT chk_amount_nonneg CHECK (discount_amount >= 0),
  ADD CONSTRAINT chk_max_amount_nonneg CHECK (max_amount IS NULL OR max_amount >= 0),
  ADD CONSTRAINT chk_max_usage_nonneg CHECK (max_usage_cnt IS NULL OR max_usage_cnt >= 0),
  ADD CONSTRAINT chk_dow_mask CHECK (dow_mask IS NULL OR dow_mask BETWEEN 0 AND 127);

-- 단위금액당 규칙 (PER_UNIT일 때만)
CREATE TABLE IF NOT EXISTS discount_per_unit_rule (
  discount_id       BIGINT PRIMARY KEY REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  unit_amount       NUMERIC(10,2) NOT NULL,   -- 얼마마다
  per_unit_value  NUMERIC(10,2) NOT NULL,   -- 단위당 얼마
  max_discount_amount NUMERIC(10,2)             -- 전체 최대 할인 금액
);

ALTER TABLE discount_per_unit_rule
  ADD CONSTRAINT chk_per_unit_nonneg CHECK (unit_amount > 0 AND per_unit_value >= 0),
  ADD CONSTRAINT chk_max_discount_nonneg CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0);

-- 적용 대상(브랜드/지점)
CREATE TABLE IF NOT EXISTS discount_applicable_brand (
  discount_id BIGINT NOT NULL REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  brand_id BIGINT NOT NULL REFERENCES brand(brand_id),
  is_excluded BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (discount_id, brand_id)
);

CREATE TABLE IF NOT EXISTS discount_applicable_branch (
  discount_id BIGINT NOT NULL REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  branch_id   BIGINT NOT NULL REFERENCES brand_branch(branch_id),
  PRIMARY KEY (discount_id, branch_id)
);

--조건별 매핑 테이블
CREATE TABLE IF NOT EXISTS discount_required_payment (
  discount_id BIGINT NOT NULL REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  payment_id     BIGINT NOT NULL REFERENCES payment_product(payment_id),
  PRIMARY KEY (discount_id, payment_id)
);
CREATE TABLE IF NOT EXISTS discount_required_telco (
  discount_id BIGINT NOT NULL REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  telco_id     BIGINT NOT NULL REFERENCES telco_provider_detail(provider_id),
  PRIMARY KEY (discount_id, telco_id)
);
CREATE TABLE IF NOT EXISTS discount_required_membership (
  discount_id BIGINT NOT NULL REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  membership_id     BIGINT NOT NULL REFERENCES membership_provider_detail(provider_id),
  PRIMARY KEY (discount_id, membership_id)
);
CREATE TABLE IF NOT EXISTS discount_required_affiliation (
  discount_id BIGINT NOT NULL REFERENCES discount_program(discount_id) ON DELETE CASCADE,
  affiliation_id      BIGINT NOT NULL REFERENCES affiliation_provider_detail(provider_id),
  PRIMARY KEY (discount_id, affiliation_id)
);

-- ========== 인덱스 ==========
-- 무결성 보장
-- 브랜드 명 중복 방지
CREATE UNIQUE INDEX IF NOT EXISTS ux_brand_name ON brand(brand_name);
-- 같은 브랜드 내 지점명 중복 방지
CREATE UNIQUE INDEX IF NOT EXISTS ux_branch_brand_name ON brand_branch(brand_id, branch_name);

CREATE INDEX IF NOT EXISTS idx_branch_name              ON brand_branch(branch_name);
CREATE INDEX IF NOT EXISTS idx_discount_provider        ON discount_program(provider_id);


/* WITH ctx AS (
  SELECT
    b.branch_id, b.merchant_id,
    CAST(:when_ts AS timestamp) AS ts,
    EXTRACT(ISODOW FROM CAST(:when_ts AS timestamp))::int AS isodow  -- 1=월 … 7=일
  FROM merchant m
  JOIN merchant_branch b ON b.merchant_id = m.merchant_id
  WHERE m.merchant_name = :brand_name
    AND (:branch_name IS NULL OR b.branch_name = :branch_name)
    AND m.is_active AND b.is_active
),
valid_discounts AS (
  SELECT dp.*
  FROM discount_program dp
  JOIN ctx ON TRUE
  WHERE dp.is_active
    AND (dp.valid_from IS NULL OR dp.valid_from <= ctx.ts::date)
    AND (dp.valid_to   IS NULL OR dp.valid_to   >= ctx.ts::date)
    AND (
      dp.dow_mask IS NULL
      OR ((dp.dow_mask & (1 << (ctx.isodow - 1))) <> 0)
    )
    AND (
      dp.time_from IS NULL OR dp.time_to IS NULL
      OR (ctx.ts::time BETWEEN dp.time_from AND dp.time_to)
    )
    AND (
      -- 대상 지정: 브랜드/지점 매칭, 또는 대상 미지정이면 전 지점 적용
      EXISTS (SELECT 1 FROM discount_applicable_merchant dam
              WHERE dam.discount_id = dp.discount_id
                AND dam.merchant_id = (SELECT merchant_id FROM ctx)
                AND dam.is_excluded = FALSE)
      OR EXISTS (SELECT 1 FROM discount_applicable_branch dab
                 WHERE dab.discount_id = dp.discount_id
                   AND dab.branch_id = (SELECT branch_id FROM ctx))
      OR (
         NOT EXISTS (SELECT 1 FROM discount_applicable_merchant dam2 WHERE dam2.discount_id = dp.discount_id)
     AND NOT EXISTS (SELECT 1 FROM discount_applicable_branch dab2 WHERE dab2.discount_id = dp.discount_id)
      )
    )
    AND (
      :channel IS NULL
      OR dp.channel_limit IS NULL
      OR dp.channel_limit = :channel
    )
)
SELECT
  vd.discount_id,
  vd.discount_name,
  p.provider_name,
  p.provider_type,
  vd.discount_type,
  vd.discount_amount,
  vd.max_amount,
  vd.required_level,          -- (개인화 없음: 필요 등급을 안내용으로 보여줌)
  vd.channel_limit,
  vd.valid_from, vd.valid_to,
  -- 카드 한정일 경우 어떤 카드가 필요한지 안내(없으면 NULL)
  COALESCE(
    (SELECT string_agg(cp.payment_name, ', ' ORDER BY cp.payment_name)
     FROM discount_payment_condition dcc
     JOIN payment_product cp ON cp.payment_id = dcc.payment_id
     WHERE dcc.discount_id = vd.discount_id),
    NULL
  ) AS required_payments,
  vd.qualification,
  vd.appliable_medu
FROM valid_discounts vd
JOIN discount_provider p ON p.provider_id = vd.provider_id
ORDER BY p.provider_type, vd.discount_name; */

